### ISSUE TITLE
Strange submit button appearance in IE 11 after including lity.css

### ISSUE THREAD

**Issue by richman555** [jsor/lity#74]
Hi, I have been using **Lity 2.0.0** for the last few days and it works great for my purposes and is lightweight.   

I have noticed a strange anomaly which doesn't seem to be a major impact for me however I wanted to add it as an issue.  Also I believe this issue might exist in other browser types however it seems most noticeable in IE (I am using version 11).

After including the file lity.css to my page, the following submit buttons appear to be 'highlighted' or 'depressed' after clicking on them and they remain this way after the click.   In my case, I am not using the submit button within a form (I use it to call other javascript  on the page without posting a form).

```
    <link href="lity.css" rel="stylesheet">
    <script src="jquery-3.1.0.js"></script>
    <script src="lity.js"></script>
```

is included on my page.   If I remove the stylesheet link the buttons then work properly.

my submit button is like the following (no form tag surrounds it) -

`<input type="submit" name="Edit" value="Edit" id="Edit" align="left" />`

When this button is clicked, it appears to stay 'highlighted' or 'depressed' in appearance.  I have many several buttons, so they all appear to stay this way.    

As I stated before, this issue appears to not break anything functionally for me, just how these submit buttons appear on the page after clicking on them.

Thanks and keep up the great work!

**Comment by johanson** [comment]
Probably it doesn't have anything to do with Lity itself, but if you want help, you should give the address of the site it happens.

**Comment by jsor** [comment]
A reproducible test case makes helping a lot easier :)

Could you first try the latest version v2.2.0? I fixed an odd behaviour with the initial focused element in v2.1.0. Maybe that's what you are experiencing here.

**Comment by richman555** [comment]
Thanks for your help guys.  As I said, this really doesn't break anything for me, just might want to take a look at it to see if its a legitimate issue.  My site at the moment is only internal running on my local machine at the moment but you can see the issue on this screenshot (notice the two highlighted edit buttons) - https://snag.gy/AFRBUn.jpg

This only starts happening once the lity.css file is included and I am using v2.2.0 which I downloaded.

I also have created a simple example using html.  There are two html files here which only display a button.   One includes lity files and one excludes them and here using IE to view it you can see the same issue where the button remains highlighted.   Obviously, if you have pages with many buttons as I do, its more noticable. 

[lityexample.zip](https://github.com/jsor/lity/files/558234/lityexample.zip)

Thanks for your help!

**Comment by jsor** [comment]
I could reproduce this behavior and it looks like it is cause by this line: https://github.com/jsor/lity/blob/master/dist/lity.css#L139

When i remove this line, the behavior disappears which really doesn't make any sense to me 😕 

I have no idea why, maybe someone else knows the cause.

**Comment by richman555** [comment]
Interesting.. When I remove this line from the lity.css the issue persists and the button remains as highlighted.  Are you certain this is the correct line?

`font-style: normal;`

Thanks for your help!

**Comment by jsor** [comment]
Heh, i've committed to master in the meantime and the lines have changed 😃 
That's the correct line: https://github.com/jsor/lity/blob/2d368cdcd51b4023baacb82bbce8f4444443991e/dist/lity.css#L139

```
.lity-close:hover,
```

**Comment by richman555** [comment]
Thanks!  Removing that line appears to work and doesn't seem to have any negative impact for how I am using it (to display lightbox with a iframe).

**Comment by richman555** [comment]
This issue can be closed unless you would like to investigate it any further, thanks for your help!
